# Generated by Django 5.1.7 on 2025-04-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('facebook_acount', models.CharField(max_length=50, null=True)),
                ('Birthdate', models.DateTimeField()),
                ('phone', models.CharField(max_length=50)),
                ('active_email', models.BooleanField(default=False)),
                ('picture', models.ImageField(default='default.jpg', upload_to='users/')),
            ],
        ),
        migrations.CreateModel(
            name='user_active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=50)),
                ('time_send', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
