# Generated by Django 5.1.7 on 2025-04-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Birthdate',
            field=models.DateTimeField(null=True),
        ),
    ]
